version: "3.4"

services:
  frontend:
    container_name: mimir_frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package-lock.json:/app/package-lock.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/@types:/app/@types
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
  backend:
    container_name: mimir_backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - 8000:8000
    environment:
      - MONGODB_URL=mongodb://mimir_mongodb:27017
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mimir_mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ~/.mongodb/db:/data/db
    ports:
      - 27018:27017
    restart: unless-stopped
